spring:
  data:
    mongodb:
      uri: ${MONGODB_URL}
      username: ${MONGODB_ADMIN_USER_NAME}
      password: ${MONGODB_ADMIN_USER_PASSWORD}
      database: ${MONGODB_USER_DB}

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8081
auth_url: ${AUTH_URL} 
use_auth: true 