spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/movies
      database: movies

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8081